ddpm:
  base_lr: 0.000025
  params:
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    num_res_blocks: 2
    num_channels: [32, 64, 128, 256]
    attention_levels: [False, True, True,True]
  scheduler:
    schedule: "scaled_linear_beta"
    num_train_timesteps: 1000
    beta_start: 0.0015
    beta_end: 0.0205
    prediction_type: "v_prediction"
data:
  train_folder: "F:/MONAI/train_g_data/ll" 
  val_folder: "F:/MONAI/valuation_g_data/ll"
run_dir: "F:/MONAI/ldm/newoupt"
perceptual_network:
  params:
    spatial_dims: 2
    network_type: "squeeze"
perceptual_weight: 0.3 
